### ISSUE TITLE
Problems with zsh

### ISSUE THREAD

**Issue by maxulysse** [vigneshwaranr/bd#11]
I tried bd in zsh.
So instead of adding the alias to the .bashrc file, I add it to my .zshrc file
Then I sourced it.
And when i tried to use bd, instead of changing the directory
I'm still in the same directory, and the name has changed, and it's : NEWPWD

**Comment by vigneshwaranr** [comment]
@MaxUlysse I'd recommend using [Tarrasch/zsh-bd](https://github.com/Tarrasch/zsh-bd) but I'm personally using zsh with bd. Just to record that I'm not facing any issues in v1.0.
