### ISSUE TITLE
OS X/BSD issues

### ISSUE THREAD

**Issue by ttscoff** [vigneshwaranr/bd#19]
I really love the idea behind `bd`, and it comes in handy a lot for me.

Just to let you know, there are some inconsistencies with the way that OS X (BSD's) `sed` and other tools work vs. GNU. For instance, the "I" flag on the regex for case sensitivity doesn't work, and in the completion file the sed substitution fails for reasons I don't understand. I was able to fix completion by using `tr` instead of `sed`:

     pwd | tr / "\n"

I ended up [redoing it completely](https://gist.github.com/ttscoff/e44bb3eff0c87bf8ae78), though, and now there's case insensitive completion and replacement, at least on Darwin with Bash 4.3.11. 

I spent a long time early this morning trying to figure out a case insensitive way to make the main script work before I realized you had already updated it. Unfortunately, your solution is one of the first ones I had to discard. I could install the GNU utils, but I'd like to think there's a solution for the OS X crowd.

I did give up and write [my own version of this utility](https://gist.github.com/ttscoff/2251ec8d7f477f7d3fd0). It's simpler, but it's suiting my needs. It assumes you always want partial matching and doesn't take all of your logic into account. It uses Ruby to handle the string parsing. A scripting language like Ruby or Perl was the only way I could get it to work for me after spending an hour wrangling around with `sed` and `awk`. Just sharing it in case you can gleam anything from it.

**Comment by vigneshwaranr** [comment]
Hi @ttscoff 

Your implementation looks cool!

BTW @janosgyerik replaced sed with perl to make bd work with OS X/BSD (see #25)

Now bd works fine everywhere.
