### ISSUE TITLE
Bash completion doesn't work on Mac OSX

### ISSUE THREAD

**Issue by dasizeman** [vigneshwaranr/bd#34]
There is a problem with the sed implementation not handling newlines in replacement strings, and this was causing problems with the bash completion script on the platform.

I have implemented a fix that seems to work on both Mac and Linux, but I have only tested CentOS on the Linux side, so someone may want to do more testing. 

Fix is in #33

**Comment by vigneshwaranr** [comment]
Tested in my mac. Works fine! Thanks for the fix. :)
