### ISSUE TITLE
bd for macOS

### ISSUE THREAD

**Issue by iefdev** [vigneshwaranr/bd#44]
_Since the updates\/acitivity here seems a bit low frequent, I make an issue istead of a PR. (Don't want a fork hanging around for too long.)_
—

If you want, you can update your ReadMe with:

    ***For OS X/macOS***

    Using [MacPorts](https://ports.macports.org/port/bd):

    ```bash
    sudo port install bd
    ```

- - -

***For OS X/macOS***

Using [MacPorts](https://ports.macports.org/port/bd):

```bash
sudo port install bd
```

**Comment by vigneshwaranr** [comment]
Thank you so much. I tested and works great! Added to the Readme 👍
